/**
 * Catálogo de equipamentos do CP2b: identificação e enquadramento de catálogo.
 *
 * Fonte única usada tanto pelo seed de desenvolvimento quanto pelo importador
 * de produção. Deliberadamente **não** carrega patrimônio nem número de série:
 * os valores originais eram sintéticos e os reais devem ser preenchidos pela
 * equipe do laboratório dentro da ferramenta.
 */
export interface Cp2bEquipmentEntry {
  readonly code: string;
  readonly name: string;
  /** Termo usado para casar o equipamento com uma opção de catálogo do laboratório. */
  readonly searchKey: string;
  readonly assetTag: string;
  readonly serialNumber: string;
  readonly notes: string;
  readonly maxMinutes: number;
  readonly requiresTraining: boolean;
}

export const CP2B_EQUIPMENT_CATALOG: readonly Cp2bEquipmentEntry[] = [
  // 1. FAPESP Equipments
  {
    code: 'EQ-ADAMO-F2DM',
    name: 'Forno Mufla Microprocessado Adamo F2-DM',
    searchKey: 'F2-DM',
    assetTag: 'FAPESP-2018-001',
    serialNumber: 'ADAMO-F2DM-01',
    notes: 'Aquisição FAPESP proc. 2016/16438-3 (AQ-001). Temperatura de trabalho até 1200°C.',
    maxMinutes: 720,
    requiresTraining: true,
  },
  {
    code: 'EQ-HACH-DR6000',
    name: 'Espectrofotômetro UV-Vis Hach DR6000',
    searchKey: 'DR6000',
    assetTag: 'FAPESP-2018-002',
    serialNumber: 'HACH-DR6000-01',
    notes: 'Aquisição FAPESP (AQ-002). Leitura UV-Vis 190 a 1100 nm.',
    maxMinutes: 480,
    requiresTraining: true,
  },
  {
    code: 'EQ-HACH-DRB200',
    name: 'Reator / Termo-Digestor Hach DRB200',
    searchKey: 'DRB200',
    assetTag: 'FAPESP-2018-003',
    serialNumber: 'HACH-DRB200-01',
    notes: 'Aquisição FAPESP (AQ-002). Bloco digestor para DQO, TOC e digestões térmicas.',
    maxMinutes: 360,
    requiresTraining: false,
  },
  {
    code: 'EQ-SHIMADZU-GC2030',
    name: 'Cromatógrafo Gasoso para Biogás Shimadzu GC-2030NS',
    searchKey: 'GC-2030NS',
    assetTag: 'FAPESP-2019-006',
    serialNumber: 'SHIMADZU-GC2030-01',
    notes: 'Aquisição FAPESP (AQ-005). Análise cromatográfica de biogás (CH4, CO2, H2S, N2, O2).',
    maxMinutes: 1440,
    requiresTraining: true,
  },
  {
    code: 'EQ-CITUA-BIO1',
    name: 'Biodigestor de 5 Litros Citua — Unidade 1',
    searchKey: 'Biodigestor de 5 litros',
    assetTag: 'FAPESP-2019-022',
    serialNumber: 'CITUA-BIO-01',
    notes: 'Aquisição FAPESP (AQ-032). Reator anaeróbio de bancada 5L.',
    maxMinutes: 4320,
    requiresTraining: false,
  },
  {
    code: 'EQ-CITUA-BIO2',
    name: 'Biodigestor de 5 Litros Citua — Unidade 2',
    searchKey: 'Biodigestor de 5 litros',
    assetTag: 'FAPESP-2019-023',
    serialNumber: 'CITUA-BIO-02',
    notes: 'Aquisição FAPESP (AQ-033). Reator anaeróbio de bancada 5L.',
    maxMinutes: 4320,
    requiresTraining: false,
  },
  {
    code: 'EQ-CITUA-ACR1',
    name: 'Reator em Acrílico com Camisa Externa Citua',
    searchKey: 'acrílico',
    assetTag: 'FAPESP-2019-024',
    serialNumber: 'CITUA-ACR-01',
    notes: 'Aquisição FAPESP (AQ-034). Reator encamisado com controle de temperatura.',
    maxMinutes: 4320,
    requiresTraining: false,
  },
  {
    code: 'EQ-CITUA-LOT-BIO5L',
    name: 'Conjunto de Reatores 5 Litros para Biomassa Citua',
    searchKey: 'Reatores para biomassa',
    assetTag: 'FAPESP-2019-035',
    serialNumber: 'CITUA-LOT-01',
    notes: 'Aquisição FAPESP (AQ-035/IT-026). Lote de reatores para digestão de biomassa.',
    maxMinutes: 4320,
    requiresTraining: false,
  },
  {
    code: 'EQ-LIMA-ANAER1',
    name: 'Reator Anaeróbio Encamisado M. Lima Engenharia',
    searchKey: 'anaeróbio confeccionado',
    assetTag: 'FAPESP-2022-025',
    serialNumber: 'LIMA-ANAER-01',
    notes: 'Aquisição FAPESP (AQ-039). Confeccionado sob projeto para digestão anaeróbia.',
    maxMinutes: 4320,
    requiresTraining: true,
  },
  {
    code: 'EQ-GERHARDT-VAP450',
    name: 'Destilador Automático Kjeldahl Gerhardt VAPODEST 450 Plus',
    searchKey: 'VAPODEST',
    assetTag: 'FAPESP-2021-007',
    serialNumber: 'GERHARDT-VAP450-01',
    notes: 'Aquisição FAPESP (AQ-006). Destilador Kjeldahl/NTK microprocessado.',
    maxMinutes: 480,
    requiresTraining: true,
  },
  {
    code: 'EQ-GERHARDT-KT8S',
    name: 'Bloco Digestor Kjeldahl Gerhardt KT 8S 230V',
    searchKey: 'KT 8S',
    assetTag: 'FAPESP-2021-008',
    serialNumber: 'GERHARDT-KT8S-01',
    notes: 'Aquisição FAPESP (AQ-006). Bloco digestor térmico de 8 provas.',
    maxMinutes: 360,
    requiresTraining: true,
  },
  {
    code: 'EQ-FRIGOBAR-01',
    name: 'Frigobar para Amostras e Reagentes Friovix',
    searchKey: 'Frigobar',
    assetTag: 'FAPESP-2019-004',
    serialNumber: 'FRIOVIX-01',
    notes: 'Aquisição FAPESP (AQ-003). Refrigeração de apoio laboratorial.',
    maxMinutes: 10080,
    requiresTraining: false,
  },
  {
    code: 'EQ-BOMBA-CENTRIFUGA-01',
    name: 'Bomba Centrífuga de Transferência',
    searchKey: 'Bomba',
    assetTag: 'FAPESP-2019-005',
    serialNumber: 'BOMBA-01',
    notes: 'Aquisição FAPESP (AQ-004).',
    maxMinutes: 240,
    requiresTraining: false,
  },
  // 2. CP2b Spatial Catalog Equipments
  {
    code: 'EQ-SHAKER-SL220',
    name: 'Incubadora Shaker com Agitação Orbital e Aquecimento Solab SL-220/E',
    searchKey: 'Incubadora Shaker',
    assetTag: 'CP2B-SHAKER-01',
    serialNumber: 'SOLAB-SL220-01',
    notes: 'Equipamento de bancada CP2b para cultivo e agitação termo-controlada.',
    maxMinutes: 1440,
    requiresTraining: true,
  },
  {
    code: 'EQ-ESTUFA-BIOEASY',
    name: 'Estufa de Secagem e Esterilização Bio Easy Digital 150 L',
    searchKey: 'Estufas 103',
    assetTag: 'CP2B-ESTUFA-01',
    serialNumber: 'BIOEASY-150L-01',
    notes: 'Estufa de secagem com circulação de ar para determinação de sólidos e umidade.',
    maxMinutes: 1440,
    requiresTraining: false,
  },
  {
    code: 'EQ-PHMETRO-KASVI',
    name: 'Medidor de pH de Bancada com ATC Kasvi',
    searchKey: 'Medidor de pH',
    assetTag: 'CP2B-PH-01',
    serialNumber: 'KASVI-PH-01',
    notes: 'pHmetro de bancada com eletrodo e compensação automática de temperatura.',
    maxMinutes: 240,
    requiresTraining: false,
  },
  {
    code: 'EQ-MOINHO-MA680',
    name: 'Moinho de Facas para Biomassa Marconi MA680/CF',
    searchKey: 'Moinho',
    assetTag: 'CP2B-MOINHO-01',
    serialNumber: 'MARCONI-MA680-01',
    notes: 'Moinho de facas com inversor de frequência para moagem e cominuição de biomassa vegetal.',
    maxMinutes: 360,
    requiresTraining: true,
  },
  {
    code: 'EQ-BALANCA-ANALITICA',
    name: 'Balança Analítica de Precisão ± 0,0001 g',
    searchKey: 'Balança analítica',
    assetTag: 'CP2B-BAL-01',
    serialNumber: 'BAL-ANALITICA-01',
    notes: 'Balança analítica com capela de proteção para pesagem de alta precisão.',
    maxMinutes: 120,
    requiresTraining: false,
  },
  {
    code: 'EQ-CENTRIFUGA-50ML',
    name: 'Centrífuga de Bancada para Tubos Falcon 50 mL',
    searchKey: 'Centrífuga de bancada',
    assetTag: 'CP2B-CENT-01',
    serialNumber: 'CENT-50ML-01',
    notes: 'Centrífuga de bancada para separação de fases e clarificação de digestato.',
    maxMinutes: 180,
    requiresTraining: false,
  },
  {
    code: 'EQ-BANHO-CIRCULACAO',
    name: 'Banho Termostático com Circulação Externa',
    searchKey: 'Banho termostático',
    assetTag: 'CP2B-BANHO-01',
    serialNumber: 'BANHO-CIRC-01',
    notes: 'Banho para termostatização de reatores encamisados.',
    maxMinutes: 1440,
    requiresTraining: false,
  },
  {
    code: 'EQ-AGITADOR-MAGNETICO',
    name: 'Agitador Magnético com Aquecimento e Chapa Aquecedora',
    searchKey: 'Agitador magnético',
    assetTag: 'CP2B-AGIT-01',
    serialNumber: 'AGIT-MAG-01',
    notes: 'Agitador magnético com controle térmico até 350°C.',
    maxMinutes: 480,
    requiresTraining: false,
  },
  {
    code: 'EQ-MEDIDOR-RITTER-TG05',
    name: 'Medidor de Vazão de Gás Ritter TG 05 Termoplástico',
    searchKey: 'Ritter',
    assetTag: 'CP2B-RITTER-01',
    serialNumber: 'RITTER-TG05-01',
    notes: 'Medidor volumétrico contínuo de fluxo de biogás.',
    maxMinutes: 4320,
    requiresTraining: false,
  },
];
